@startuml
|Раздел Журнал регистрации абонента|
start
:Добавить заявление (P_UDO_PLORA_INSERT);
:Добавить сотрудника (P_UDO_PLORAE_INSERT);
:Добавить направление (P_UDO_PLORAD_INSERT);
:Отправить (P_UDO_PLORA_SEND); 
|#AntiqueWhite|Сетевые задания|
:Добавить сертификат в Очередь отправки файла (P_UDO_PLOFO_INSERT);
|Перекладчики|
:Обработать событие окончания отправки файла (ГУИД файла сертификата) (P_UDO_PLOFO_EXEC);
|Сетевые задания|
:Добавить заявление в Исходящие события (P_UDO_PLOEO_INSERT);
|Перекладчики|
:Обработать событие окончания отправки (ГУИД абонента) (P_UDO_PLOEO_EXEC);
stop
@enduml
