@startuml
hide empty description

state "Успешный ход проверки ФЛК" as Saccess #LightGray;line.dotted;line:LightGray {
    state "1 - Требуется ФЛК" as State1
    state "2 - В обработке ФЛК" as State2  
    state "3 - Проверка пройдена" as State3
}
state "Ошибки" as Errors #LightGray;line.dotted;line:LightGray {
    state "4 - Проверка не пройдена" as State4
    state "5 - Ошибка ФЛК" as State5
}

[*] --> State1

State1 -> State2

State2 -> State3
State2 -> State4
State2 --> State5

State4 --> [*]
State5 --> [*]

State3 --> [*]

@enduml
