@startuml
hide empty description
state "Успешный ход регистрации" as Saccess #LightGray;line.dotted;line:LightGray {
    state "0 – Формирование" as State0
    state "1 – Разбор сертификата" as State1
    state "2 - В обработке" as State2
    state "3 - Завершен" as State3
}
state "Ошибки" as Errors #LightGray;line.dotted;line:LightGray {
    state "4 - Ошибка разбора сертификата" as State4
    state "5 - Ошибка обработки" as State5
}

[*] --> State0
State0 -> State1
State0 -> State2
State0 -> State5

State1 -> State2
State1 --> State4

State2 -> State3
State2 --> State5

State4  --> [*]
State5  --> [*]

State3 --> [*]

@enduml
