@startuml
|Раздел Журнал регистрации абонента|
start
:Добавить Журнал регистрации абонентов;
:Добавить Регистрацию сотрудника;
:Добавить Регистрацию направления;
:Отправить; 
|#AntiqueWhite|Сетевые задания|
:Добавить сертификат в Очередь отправки файла;
|Перекладчики|
:Обработать ответ (ГУИД файла сертификата);
|Сетевые задания|
:Добавить заявление в Исходящие события;
|Перекладчики|
:Обработать ответ (ГУИД абонента);
stop
@enduml
