@startuml
hide empty description

state "Успешный ход получения ПФ" as Saccess #LightGray;line.dotted;line:LightGray {
    state "1 - Затребована ПФ" as State1
    state "2 - ПФ получена" as State2
}
state "Ошибки" as Errors #LightGray;line.dotted;line:LightGray {
    state "3 - Ошибка ПФ" as State3
}

[*] -> State1

State1 -> State2

State1 -> State3

State2 --> [*]

State3 --> [*]

@enduml
