@startuml
scale 100 width
scale 260 height

hide empty description
state "Успешный ход получения входящих документов от контролирующих органов" as Saccess #LightGray;line.dotted;line:LightGray {
    state "1 – Получено\nсобытие\nдешифрования" as State1
    state "2 - Постановка\nшифрованных\nдокументов\nна получение" as State2
    state "3 - Шифрованные\nдокументы\nв очереди" as State3
    state "4 - Требуется\nдешифровать\nдокументы" as State4
    state "5 - Постановка\nрасшифрованных\nдокументов\nв очередь" as State5
    state "6 - Расшифрованные\nдокументы\nв очереди" as State6
    state "7 - Постановка\nсобытия\nрезультата\nдешифрования\nв очередь" as State7
    state "8 - Событие\nрезультата\nдешифрования\nв очереди" as State8
    state "9 - Событие\nрезультата\nдешифрования\nотправлено в СПО" as State9
    state "10 – Получено\nсобытие\nс исходными\nдокументами" as State10
    state "11 - Постановка\nисходных\nдокументов\nна получение" as State11
    state "12 - Исходные\nдокументы\nв очереди\nна получение" as State12
    state "13 - Входящие\nдокументы\nполучены" as State13
    state "14 - Постановка\nзапроса\nпечатных форм\nв очередь" as State14
    state "15 - Запрос\nпечатных форм\nв очереди" as State15
    state "16 - Запрос\nпечатных форм\nотправлен\nв сервис отчетности" as State16
    state "17 – Получено\nсобытие\nна получение\nпечатной формы" as State17
    state "18 - Постановка\nпечатных форм\nна получение" as State18
    state "19 - Печатные\nформы\nв очереди\nна получение" as State19
    state "20 - Печатные\nформы\nполучены" as State20
}
state "Ошибки при получении входящих документов от контролирующих органов" as Errors #LightGray;line.dotted;line:LightGray {
    state "21 - Ошибка\nпостановки\nшифрованных\nдокументов\nна получение" as State21
    state "22 - Ошибка\nполучения\nшифрованных\nдокументов" as State22
    state "23 - Ошибка\nдешифрования\nдокументов" as State23
    state "24 - Ошибка\nпостановки\nрасшифрованных\nдокументов\nв очередь" as State24
    state "25 - Ошибка\nотправки\nрасшифрованных\nдокументов\nв СПО" as State25
    state "26 - Ошибка\nпостановки\nсобытия\nрезультата\nдешифрования\nв очередь" as State26
    state "27 - Ошибка\nотправки\nсобытия\nрезультата\nдешифрования\nв СПО" as State27
    state "28 - Ошибка\nполучения\nсобытия\nс исходными\nдокументами" as State28
    state "29 - Ошибка\nпостановки\nисходных\nдокументов\nна получение\nв очередь" as State29
    state "30 - Ошибка\nполучения\nисходных\nдокументов\nиз СПО" as State30
    state "31 - Ошибка\nпостановки\nзапроса\nпечатных форм\nв очередь" as State31
    state "32 - Ошибка\nотправки\nзапроса\nпечатных форм\nв сервис отчетности" as State32
    state "33 – Ошибка\nполучения\nсобытия\nна получение\nпечатной формы" as State33
    state "34 - Ошибка\nпостановки\nпечатных форм\nна получение" as State34
    state "35 - Ошибка\nполучения\nпечатных форм" as State35
}

[*] --> State1
State1 -> State2

State2 -> State3
State2 --> State21

State3 -> State4
State3 --> State22

State4 -> State5
State4 --> State23

State5 -> State6
State5 --> State24

State6 -> State7
State6 --> State25

State7 -> State8
State7 --> State26

State8 -> State9
State8 --> State27

State9 -> State10
State9 --> State28

State10 -> State11

State11 -> State12
State11 --> State29

State12 -> State13
State12 --> State30

State13 -> State14

State14 -> State15
State14 --> State31

State15 -> State16
State15 --> State32

State16 -> State17
State16 -> State33

State17 -> State18

State18 -> State19
State18 --> State34

State19 -> State20
State19 --> State35

State21  --> [*]
State22  --> [*]
State23 --> [*]
State24 --> [*]
State25 --> [*]
State26 --> [*]
State27  --> [*]
State28  --> [*]
State29 --> [*]
State30 --> [*]
State31 --> [*]
State32  --> [*]
State33  --> [*]
State34 --> [*]
State35 --> [*]

State20 --> [*]

@enduml
