@startuml
scale 100 width
scale 260 height

hide empty description
state "Успешный ход получения входящих документов от контролирующих органов" as Saccess #LightGray;line.dotted;line:LightGray {
    state "1 – Получено\nсобытие\nдешифрования" as State1
    state "2 - Постановка\nшифрованных\nдокументов\nна получение" as State2
    state "3 - Шифрованные\nдокументы\nв очереди" as State3
    state "4 - Требуется\nдешифровать\nдокументы" as State4
    state "5 - Постановка\nрасшифрованных\nдокументов\nв очередь" as State5
    state "6 - Расшифрованные\nдокументы\nв очереди" as State6
    state "7 - Постановка\nсобытия\nрезультата\nдешифрования\nв очередь" as State7
    state "8 - Событие\nрезультата\nдешифрования\nв очереди" as State8
    state "9 - Событие\nрезультата\nдешифрования\nотправлено в СПО" as State9
    state "10 – Получено\nсобытие\nс исходными\nдокументами" as State10
    state "11 - Постановка\nисходных\nдокументов\nна получение" as State11
    state "12 - Исходные\nдокументы\nв очереди\nна получение" as State12
    state "13 - Входящие\nдокументы\nполучены" as State13
}
state "Ошибки при получении входящих документов от контролирующих органов" as Errors #LightGray;line.dotted;line:LightGray {
    state "14 - Ошибка\nпостановки\nшифрованных\nдокументов\nна получение" as State14
    state "15 - Ошибка\nполучения\nшифрованных\nдокументов" as State15
    state "16 - Ошибка\nдешифрования\nдокументов" as State16
    state "17 - Ошибка\nпостановки\nрасшифрованных\nдокументов\nв очередь" as State17
    state "18 - Ошибка\nотправки\nрасшифрованных\nдокументов\nв СПО" as State18
    state "19 - Ошибка\nпостановки\nсобытия\nрезультата\nдешифрования\nв очередь" as State19
    state "20 - Ошибка\nотправки\nсобытия\nрезультата\nдешифрования\nв СПО" as State20
    state "21 - Ошибка\nполучения\nсобытия\nс исходными\nдокументами" as State21
    state "22 - Ошибка\nпостановки\nисходных\nдокументов\nна получение\nв очередь" as State22
    state "23 - Ошибка\nполучения\nисходных\nдокументов\nиз СПО" as State23
}

[*] --> State1
State1 -> State2

State2 -> State3
State2 --> State14

State3 -> State4
State3 --> State15

State4 -> State5
State4 --> State16

State5 -> State6
State5 --> State17

State6 -> State7
State6 --> State18

State7 -> State8
State7 --> State19

State8 -> State9
State8 --> State20

State9 -> State10
State9 --> State21

State10 -> State11

State11 -> State12
State11 --> State22

State12 -> State13
State12 --> State23

State14  --> [*]
State15  --> [*]
State16 --> [*]
State17 --> [*]
State18 --> [*]
State19 --> [*]
State20  --> [*]
State21  --> [*]
State22 --> [*]
State23 --> [*]

State13 --> [*]

@enduml
