@startuml

class "Журнал регистрации абонентов" as MasterClass {
..Пользовательские действия..
{method}+Добавить заявление (P_UDO_PLORA_INSERT)
{method}+Просмотр (P_UDO_PLORA_VIEW)
{method}+Удалить (P_UDO_PLORA_DELETE)
{method}+Отправить (P_UDO_PLORA_SEND)
..Методы транспорта..
{method}+Завершить формирование P_UDO_PLORA_FINFRM
}

class "Регистрация сотрудников" as SpecClass1 {
..Пользовательские действия..
{method}+Добавить сотрудника (P_UDO_PLORAE_FRM)
{method}+Просмотр (P_UDO_PLORAE_VIEW)
{method}+Удалить сотрудника (P_UDO_PLORAE_DELETE)
..Методы транспорта..
{method}+Добавить сертификат P_UDO_PLORAE_CRCERT
{method}+Ошибка разбора сертификата P_UDO_PLORAE_ERR_CERT
}

class "Регистрация направлений" as SpecClass2 {
..Пользовательские действия..
{method}+Добавить направление (P_UDO_PLORAD_CON)
{method}+Просмотр (P_UDO_PLORAD_VIEW)
{method}+Исправить направление (P_UDO_PLORAD_UPDATE)
}

class "Сетевые задания регистрации" as SpecClass3 {
..Пользовательские действия..
{method}+Просмотр (P_UDO_PLORAN_VIEW)
{method}+Результаты (P_UDO_PLORAN_RES)
}

MasterClass "1" *-- "много" SpecClass1
MasterClass "1" *-- "много" SpecClass2
MasterClass "1" *-- "много" SpecClass3

@enduml
