@startuml
hide empty description
state "Успешный ход регистрации" as Saccess #LightGray;line.dotted;line:LightGray {
    state "0 – Формирование" as State0
    state "1 – Разбор сертификата" as State1
    state "2 - Постановка сертификата в очередь" as State2
    state "3 - Сертификат в очереди" as State3
    state "4 - Постановка заявления в очередь" as State4
    state "5 - Заявление в очереди" as State5
    state "6 - Заявление отправлено" as State6
    state "7 - Получен ответ" as State7
}
state "Ошибки" as Errors #LightGray;line.dotted;line:LightGray {
    state "8 - Ошибка разбора сертификата" as State8
    state "9 - Ошибка постановки сертификата в очередь" as State9
    state "10 - Ошибка отправки сертификата" as State10
    state "11 - Ошибка постановки заявления в очередь" as State11
    state "12 - Ошибка отправки заявления" as State12
    state "13 - Ошибка получения ответа" as State13
}

[*] --> State0
State0 -> State1
State0 -> State2
State0 -> State4

State1 -> State2
State1 --> State8

State2 -> State3
State2 --> State9

State3 -> State4
State3 --> State10

State4 -> State5
State4 --> State11

State5 -> State6
State5 --> State12
State12 --> State7

State6 -> State7
State6 --> State13
State13 --> State7

State8  --> [*]
State9  --> [*]
State10 --> [*]
State11 --> [*]
State12 --> [*]
State13 --> [*]

State7 --> [*]

@enduml
